### ISSUE TITLE
Login/ Registration

### ISSUE THREAD

**Issue by mai2161** [vaghani-shreya/EECS_2311_Group_Project#12]
If I register as a new user without a proper email address and I happen to forget my password. Then a verification code will not be sent. One way we could fix this is by mentioning to the user that they must sign up with an email address or add into the algorithm that the username must be a proper email address.

**Comment by ElizabethGhreir** [comment]
Method added to check if the username is a valid email address. Only valid usernames/emails will be able to register as new users.
