### ISSUE TITLE
Email Password encryption

### ISSUE THREAD

**Issue by mai2161** [vaghani-shreya/EECS_2311_Group_Project#13]
If I want the email to be sent to me I have to get the password and enter it manually for the “From” field in the sendEmail method in the newsletter.java file. So it is not public when pushed to github. There may be better ways to store it more securely so this doesn’t have to be manual. So that it can be retrieved automatically.

**Comment by anushamasroor** [comment]
In this phase we did not focus on the security aspect of the project (in terms of encrypting files) we focused more on the implementation of user stories. This will be addressed in the next phase of the project.
