### ISSUE TITLE
Limit the query in the sorting list.

### ISSUE THREAD

**Issue by vaghani-shreya** [vaghani-shreya/EECS_2311_Group_Project#14]
At the moment, when we try to filter and sort the TV Shows/Movies by the filters, the whole list from the database is being displayed including the ones which are not displayed when there are no filters on. 
Change the query to filter it from the displayed list and not from the whole database.

**Comment by ElizabethGhreir** [comment]
A limit was added to the query getting pulled for the filter and sort
