### ISSUE TITLE
Add an Ok button at the filter/Sort

### ISSUE THREAD

**Issue by vaghani-shreya** [vaghani-shreya/EECS_2311_Group_Project#15]
Currently when sorting, the list gets sorted as soon as we click on the filter from the drop down. For more clarity, it would be better if we had an "Ok" button that when clicked would display the list according to the filter by the user.

**Comment by ElizabethGhreir** [comment]
Sort button added after dropdown menu
![image](https://github.com/vaghani-shreya/EECS_2311_Group_Project/assets/52081669/685954d3-bfaa-41c8-bcc8-95a903d79720)
