### ISSUE TITLE
comment for show disappears after the popup window is closed

### ISSUE THREAD

**Issue by ElizabethGhreir** [vaghani-shreya/EECS_2311_Group_Project#18]
**_Bug Report for Rating Feature_**
**Reported by:** Elizabeth
**Date reported:** 3/24/2024
**Program (or component) name:** Add a comment for a show (rating feature)
**Version (build) identifier:** ITR3 
**Report type:** code issue
**Can reproduce**: yes 
**Severity**: low/medium
**Priority**: medium 
**Problem summary:** After the user adds a comment for show, it is displayed on the rating’s screen then it disappears shortly after
**Problem description and how to reproduce it:** 
1. Navigate to the rating page, then press on any show
2. Type a message in the comment textbox then press save
3. The message is saved in the database, and it is displayed under the rating page for that show
4. Close the pop-up window for that show, then open it again
5. The saved comment is not displayed anymore

**Comment by vaghani-shreya** [comment]
There was a misunderstanding in the implementation of the feature. The comment is supposed to disappear as it is overridden by the user
