### ISSUE TITLE
Ratings value doesn't get displayed after saved

### ISSUE THREAD

**Issue by ElizabethGhreir** [vaghani-shreya/EECS_2311_Group_Project#19]
**_Bug Report for Rating Feature_**
**Reported by**: Elizabeth
**Date reported**: 3/24/2024
**Program (or component) name**: Add a rating for a show (rating feature)
**Version (build) identifier**: ITR3
**Report type**: design issue
**Can reproduce**: yes 
**Severity**: low/medium
**Priority**: medium 
**Problem summary**: after the user rates the show the value isn’t displayed on the screen
**Problem description and how to reproduce it**: 
1. Navigate to the rating page, then press on any show
2. Type a valid integer in the rating textbox then press save
3. The value is saved to the database, however, it is not displayed on the Add rating pop-up

**Comment by vaghani-shreya** [comment]
Rating's value along with the username gets displayed. It is fixed now
