### ISSUE TITLE
Entering a different username in verification step during forget password process

### ISSUE THREAD

**Issue by ElizabethGhreir** [vaghani-shreya/EECS_2311_Group_Project#20]
**_Bug Report for Forget Password Feature_**
**Reported by:** Elizabeth
**Date reported:** 3/24/2024
**Program (or component) name**: Forget my password feature
**Version (build) identifier**: ITR3 
**Report type**: design issue
**Can reproduce**: yes 
**Severity**: medium
**Priority**: medium 
**Problem summary**: Entering the wrong username in the validation step, the prompt says the password is successfully changed when it’s not
**Problem description and how to reproduce it:** 
1. Click on “Forgot my password” from the login page
2. Enter a valid username
3. When you get to the verification page, you are asked to re-enter your username and the verification code
4. Enter a different username (not the correct one), and enter the verification code
5. Click enter
6. A successful message appears that the password has been successfully changed, however, the password has not changed since the username was not entered correctly in step 4

**Suggested fix**: one possible solution would be to remove the username altogether from Step 3

**Comment by anushamasroor** [comment]
I added a method to check if the username is correct. If it is not correct then the program will not allow you to change your password.
