### ISSUE TITLE
Analytics page is not scalable

### ISSUE THREAD

**Issue by ElizabethGhreir** [vaghani-shreya/EECS_2311_Group_Project#21]
**_Bug Report for Analytics Page_**
**Reported by:** Elizabeth
**Date reported:** 3/24/2024
**Program (or component) name**: Analytics Page
**Version (build) identifier**: ITR3 
**Report type**: design issue
**Can reproduce**: yes 
**Severity**: high
**Priority**: high 
**Problem summary**: The Analytics page is too wild and too big, so the chart gets cut off
**Problem description and how to reproduce it:**  Navigate to the Analytics page

**Comment by vaghani-shreya** [comment]
Solved.
