### ISSUE TITLE
In Dashboard issue with drop-down menu "genre"

### ISSUE THREAD

**Issue by anushamasroor** [vaghani-shreya/EECS_2311_Group_Project#22]
**Bug Report for Dashboard Feature**
**Reported By:** Anusha Masroor
**Date Reported**: 03/24/2024
**Program (or component) name:** Show discovery
**Version (build) Identifier:** ITR 3
**Report Type**: Coding Issue
**Can reproduce:** Yes
**Severity:** Medium
**Priority:** Medium
**Problem Summary:** When the drop-down menu genre is selected, and you search for a show/movie based on genre no shows/movies appears
**Problem Description and how to reproduce it:**
1.	Navigate to the drop-down menu beside the search bar on the dashboard.
2.	Select genre from the drop-down menu.
3.	Type in a genre in the search bar and press search
4.	No results are displaying on the dashboard screen

**Comment by ElizabethGhreir** [comment]
![image](https://github.com/vaghani-shreya/EECS_2311_Group_Project/assets/52081669/e0dca326-c7d9-4a55-8e53-444e43075567)
issue fixed
