### ISSUE TITLE
Favorites list does not match format with other tabs 

### ISSUE THREAD

**Issue by anushamasroor** [vaghani-shreya/EECS_2311_Group_Project#23]
**Bug Report for Favorites Feature**
**Reported By:** Anusha Masroor
**Date Reported:** 03/24/2024
**Program (or component) name:** favorites list
**Version (build) Identifier:** ITR 3
**Report Type:** design Issue
**Can reproduce:** Yes
**Severity:** low
**Priority:** low
**Problem Summary:** When more than 7 movies are added to the favorites list it scroll through the movies even though there is enough space on the tab to show more movies
**Problem Description and how to reproduce it:**
1.	Add more than 7 movies to favorites list from the dashboard
2.	Navigate to favorites tab
3.	Click on the square containing the favorites list a scroll bar should appear to look though all the movies

**Comment by ElizabethGhreir** [comment]
This issue has been fixed if more than 7 shows are added, then the container expands in size. The container doesn't have a specific size anymore, so the scroll bar is not being used.
