### ISSUE TITLE
New rating does not display on page immediately

### ISSUE THREAD

**Issue by anushamasroor** [vaghani-shreya/EECS_2311_Group_Project#24]
**Bug Report for Rating Feature**
**Reported By:** Anusha Masroor
**Date Reported:** 03/24/2024
**Program (or component) name:** Add a rating for a show/movie (Rating feature)
**Version (build) Identifier:** ITR 3
**Report Type:** Design Issue
**Can reproduce:** Yes
**Severity:** Medium
**Priority:** Medium
**Problem Summary:** After a user rates the movie/show the new rating does not appear on the screen
**Problem Description and how to reproduce it:**
1.	Navigate to the rating page, click on any show.
2.	Enter a new rating for the show with a valid integer value.
3.	The new rating is saved into the database, but it does not appear on the screen as the new rating.

**Comment by vaghani-shreya** [comment]
New rating along with the username is displayed. It is fixed now
